import { NextResponse } from 'next/server'
import { getUserFromRequest } from '@/lib/auth'

export const dynamic = 'force-dynamic'

export async function GET(request) {
  try {
    const user = await getUserFromRequest(request)
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    return NextResponse.json({
      success: true,
      flashcards: user.flashcards || []
    })
  } catch (error) {
    console.error('Flashcards GET Error:', error)
    return NextResponse.json({ error: 'Server error retrieving flashcards' }, { status: 500 })
  }
}

export async function POST(request) {
  try {
    const user = await getUserFromRequest(request)
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { flashcard, flashcards } = body || {}

    if (!user.flashcards) {
      user.flashcards = []
    }

    // 1. Bulk addition of flashcards (e.g. generated by AI)
    if (Array.isArray(flashcards)) {
      flashcards.forEach(card => {
        if (card.front && card.back) {
          user.flashcards.push({
            front: card.front,
            back: card.back,
            difficulty: card.difficulty || 'medium',
            nextReviewDate: new Date()
          })
        }
      })
    } 
    // 2. Add or update a single flashcard
    else if (flashcard) {
      if (flashcard._id || flashcard.id) {
        // Update existing flashcard
        const cardId = flashcard._id || flashcard.id
        const existingCard = user.flashcards.id(cardId)
        if (existingCard) {
          if (flashcard.front !== undefined) existingCard.front = flashcard.front
          if (flashcard.back !== undefined) existingCard.back = flashcard.back
          if (flashcard.difficulty !== undefined) existingCard.difficulty = flashcard.difficulty
          if (flashcard.nextReviewDate !== undefined) existingCard.nextReviewDate = new Date(flashcard.nextReviewDate)
        }
      } else if (flashcard.front && flashcard.back) {
        // Add new single flashcard
        user.flashcards.push({
          front: flashcard.front,
          back: flashcard.back,
          difficulty: flashcard.difficulty || 'medium',
          nextReviewDate: new Date()
        })
      }
    } else {
      return NextResponse.json({ error: 'Missing flashcard or flashcards payload' }, { status: 400 })
    }

    await user.save()

    return NextResponse.json({
      success: true,
      flashcards: user.flashcards
    })
  } catch (error) {
    console.error('Flashcards POST Error:', error)
    return NextResponse.json({ error: 'Server error saving flashcards' }, { status: 500 })
  }
}
